name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  tests-3x:
    name: Python ${{ matrix.py-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        py-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run tests for ${{ matrix.py-version }}
        run: pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

  tests-27:
    name: Python 2.7 on ubuntu-20.04
    runs-on: ubuntu-20.04
    container:
      image: python:2.7-buster

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run tests for 2.7
        run: pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
