name: tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  tests-3x:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m pip install -e .[dev]
      - name: "Run tests for ${{ matrix.python-version }}"
        run: python -m pytest
      - name: Upload coverage to Codecov
        uses: "codecov/codecov-action@v3"

  tests-27:
    name: "Python 2.7 on ubuntu-20.04"
    runs-on: ubuntu-20.04
    container:
      image: python:2.7-buster

    steps:
      - uses: "actions/checkout@v3"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m pip install -e .[dev]
      - name: "Run tests for 2.7"
        run: python -m pytest
      - name: Upload coverage to Codecov
        uses: "codecov/codecov-action@v3"
